#+TITLE:     Installing Immutant

* Introduction

  There are currently two options for installing Immutant: using the 
  Leiningen plugin and downloading a zip file.

* Installation via Leiningen

  To install Immutant via the [[http://leiningen.org/][Leiningen]] plugin, you'll need to first
  install Leiningen, followed by the [[https://github.com/immutant/lein-immutant/][lein-immutant]] plugin.  The plugin
  supports both Leiningen 2.0.0 or higher.  To install the plugin
  under 2.x, you'll need to add it to the plugin list in
  =~/.lein/profiles.clj=:

  #+begin_src clojure
    {:user {:plugins [[lein-immutant "VERSION"]]}}
  #+end_src

  You can determine the current version of the plugin by looking at
  its [[http://clojars.org/lein-immutant][page on clojars]].

  The plugin provides a number of subcommands, one of which is
  =install=. So installing Immutant is as easy as this:
  
  #+begin_src sh
   $ lein immutant install [VERSION]
  #+end_src
  
  Without a VERSION specified, the most recent versioned release
  will be installed. 

  To obtain a specific version, you can specify an incremental build
  number (ex: =123=) or a released version (ex: =1.0.0.Beta1=). As a
  shortcut, you can install the latest incremental build by specifying
  =:latest=.

  Releases installed via the plugin are installed by default under
  =~/.lein/immutant/releases=, and =~/.lein/immutant/current= is 
  linked to that release. You can specify an alternative parent install
  directory by passing it as the third argument to =install=:

  #+begin_src sh
   $ lein immutant install VERSION /path/where/you/want/it  
  #+end_src

  The plugin will install Immutant there, and link =~/.lein/immutant/current=
  to that version.

  This installed version of Immutant is shared across all Immutant applications
  on your machine, and does not need to be installed for each application.

  #+begin_src sh
   $ lein immutant install [VERSION]
  #+end_src

  See [[./deployment.html][Deployment]] for more details about the plugin.

* Installation via Zip Download

  You can manually download any of the same builds that you can install 
  via the plugin. You can download incremental builds from our [[http://immutant.org/builds/][builds page]]
  and an official releases from our [[http://immutant.org/releases/][releases page]].
  
  Once you have the zip downloaded, expand it somewhere handy. If you want
  to use the Leiningen plugin with this build, you'll need to set =$IMMUTANT_HOME=:

  #+begin_src sh
    $ mkdir immutant-releases
    $ cd immutant-releases
    $ unzip path/to/immutant-dist-slim.zip
    $ export $IMMUTANT_HOME=~/immutant-releases/immutant-0.10.0-slim/
  #+end_src
